site_name: Your MindGraph

theme: 
  name: material
  palette: 
    scheme: default
    primary: green
    accent: teal


plugins:
  - macros
  - markmap

nav:
  - Home: 'index.md'

extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences